import type { Metadata } from "next";
import { Inter } from "next/font/google";
import EditorNavbar from "@/components/editor/EditorNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative dark ${inter.className} w-screen overflow-hidden`}
      >
        <div className="fixed  top-0 w-full">
          <EditorNavbar />
        </div>
        <div className={"h-[calc(100vh-80px)] w-full relative top-[80px] "}>
          {children}
        </div>
      </body>
    </html>
  );
}
